### ISSUE TITLE
package.json fora de padrao, inicie por um npm init

### ISSUE THREAD

**Issue by gabrielmancini** [bc-fullstack-01/EdnoAlmeida-backend#1]
https://github.com/bc-fullstack-01/EdnoAlmeida-backend/blob/3246734dc97950ede732a6924c3d2485415d86e4/backend/package.json#L1

**Comment by edno2819** [comment]
Eu não entendi. Eu criei o repositorio usando yarn e ele configurou o package.json.

**Comment by gabrielmancini** [comment]
entendi, tudo bem entao ^^
